#import './StatusFragment.gql'

mutation generatePasswordResetToken($resetPassword: RequestResetPasswordInput!) {
  generatePasswordResetToken(resetPasswordInput: $resetPassword) {
    ...status
  }
}
